### ISSUE TITLE
LittleBigPlanet 3 Community Card broken

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/project-lighthouse#73]
the lighthouse server does not have support for the community section in LBP3, the only thing that appears in it is the search option

**Comment by alkalinethunder** [comment]
This is a known issue - it seems that LBP 3's community screen tries to hit a different endpoint that either isn't supported by Lighthouse or LBP 3 expects a differently-formatted response. I was going to look into this in October but I could never figure it out with existing packet captures. Seems to be something to do with `/LITTLEBIGPLANETPS3_XML/search` though, since the game constantly spams that when you go into the Community screen. Does the same with `/LITTLEBIGPLANETPS3_XML/genres` too if you go there.

**Comment by jvyden** [comment]
Oops, forgot to close this.
