### ISSUE TITLE
Random LBP3 crash

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/project-lighthouse#74]
LittleBigPlanet 3 sometimes crashes when you are on the main menu while connected to the server, this did not happen before

**Comment by alkalinethunder** [comment]
This has always happened to me during implementing the digest key system. Though it only seemed to happen if I manually connected to Lighthouse, instead of just letting the game connect as it first launches (like it would with official servers). Is this the case for you as well? If so, this may already be a known issue.

**Comment by jvyden** [comment]
> This has always happened to me during implementing the digest key system. Though it only seemed to happen if I manually connected to Lighthouse, instead of just letting the game connect as it first launches (like it would with official servers). Is this the case for you as well? If so, this may already be a known issue.

This is the case for me as well even today, probably a bug in the game out of our control. It *is* LBP3, after all.
